### ISSUE TITLE
Terminal Font

### ISSUE THREAD

**Issue by HirAvanCniK** [EDDYMENS/interactive-terminal#2]
Hi, I was trying to use this repository I am very fascinated by it, so kudos for this project, however the thing I didn't understand how to do was to put the "real" terminal font on the one in the web page also trying with "font-family" and importing the font doesn't work, I wanted to know if it was possible, either to have the font imported by itself automatically in the web page or even importing the font file set it to the one you see in the web page. Thanks and again congratulations on this project! 😋

**Comment by EDDYMENS** [comment]
@HirAvanCniK Thanks!, At the moment the font from the "real" terminal does not automatically get used with the terminal in your browser.

You can however set up the font of xtermJS https://github.com/xtermjs/xterm.js/issues/1534#issuecomment-404125484

Which means if you know the font used on the "real" terminal you can set it for the xtermJS
