### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by farhadazimi** [EDDYMENS/interactive-terminal#3]
After running this project, I got this message in the browser.
Upgrade Required.

What should be done to solve this problem?

**Comment by EDDYMENS** [comment]
@farhadazimi can you share a screenshot?

**Comment by farhadazimi** [comment]
of course.

And this result:
![result](https://github.com/EDDYMENS/interactive-terminal/assets/37225599/10cbead7-92e6-46b2-a713-0a02b47a17da)

**Comment by farhadazimi** [comment]
Of course

There is version and running status:
![version](https://github.com/EDDYMENS/interactive-terminal/assets/37225599/021a8837-22f7-437f-97f5-2c367e559064)

And result:
![result](https://github.com/EDDYMENS/interactive-terminal/assets/37225599/df707b8b-553b-4488-b6ed-fc58b3bf0dd0)

**Comment by EDDYMENS** [comment]
@farhadazimi are you viewing the index.html page under a server? What happens if you just open the index.html file using the file system path?
